/*
 * This source file was generated by the Gradle 'init' task
 */
package game;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        System.out.println("NIGGERS IN TESTHOLE");
    }
}
